version=${project.version}
commit=${frostguard.build.commit}
buildTime=${maven.build.timestamp}
pullRequestBuild=${frostguard.pull-request-build}
authenticodePublisher=${frostguard.update.authenticode-publisher}
